### ISSUE TITLE
Implement map Class of server

### ISSUE THREAD

**Issue by ACHinrichs** [Artilleriespiel/Artilleriespiel#3]

**Comment by sengels1997** [comment]
Needs to be reviewed. Errors depending on seed. Map usually looks a little weird.
![pictureofmap](https://cloud.githubusercontent.com/assets/3171697/12378601/2ef0e1d0-bd43-11e5-9739-7de22bf1c9d7.png)

**Comment by sengels1997** [comment]
Adrian's Graphical Map can be used for debugging purposes.
